# Generated by Django 5.2.4 on 2025-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('age', models.IntegerField(null=True)),
                ('city', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sample/')),
                ('doc', models.FileField(blank=True, null=True, upload_to='sample1/')),
            ],
        ),
    ]
