# Generated by Django 5.2.4 on 2025-08-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='address',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='city',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='age',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='data',
            name='event',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='data',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
    ]
