# Generated by Django 5.2.4 on 2025-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application4', '0002_rename_address_data_date_rename_city_data_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.IntegerField(default='', max_length=30),
        ),
    ]
