# Generated by Django 5.2.4 on 2025-08-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application4', '0003_alter_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(default='', max_length=30),
        ),
    ]
